dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: OsVKGpC5q7BsjTD+tpJf71DZpaXT1/g3XJr3M9LQp7Nn1PNuP3HRx0+6WkNfs3/TAR/64MwWD5UmJd2jT4N56HA51Zob872wVteL6fxri4vpvaYLbgbstSenCnccRZnkmJq6nh9a9k/nXGVc8T9s9r+VGIC2Y+VhLo9xxp5jSO0bhXjPeSwhN96MI3AUSVZmq376lgvmLAO0lr5xkqm1kugsbtAlwJYyjiLlF3m6hRAZq0+Q6ETVdiRWFqjTVWQKQsuDf8+pIaDZ/RO0/NacXR7hJXET8+mfzeds1JC9S07/DAury+ZKD6ewPAaFQ/d+35fh43adoJJ2A8YqI20uvrmBnt9yKuTx1flbPwo6S0lpcDUMRh4n/igDRc15/Fvql5Xkx0cyqC27yuuG9F/HzJwOBM332wkQWij997+rshhXcwqhECh3yjaszEyBvVyElh9LX/PBP0eUvX0i38pcZDIDkk4ci2GNI/DFUQjEY+2sxnhPZWGhAYAnVa2tbnLLsd3fkvycVJbuMsMVGeUVNzATkQu6jNVmbOVwIMsVN/RaqQnGSFHQzWoaMFdHMldNPzwOv2a2omw8kCvwKe/AHlea3Dt2rk+1ixMIHz9u2TGCAuPB8E4sksf9UgzKrxSHLpAYsgHkNrfqOIUVcV3T0K5Ow1fOt1SmYm3qTY2ZPN0=
